Repository facebook/facebook-swift-sdk, pull requests merged in 2019-04, with the labels that each got.

#386 Updated to support Xcode 10.2 (latest)
  FacebookSwift.xcodeproj/project.pbxproj
  FacebookSwift.xcodeproj/xcshareddata/xcschemes/FacebookCore.xcscheme
  FacebookSwift.xcodeproj/xcshareddata/xcschemes/FacebookLogin.xcscheme
  FacebookSwift.xcodeproj/xcshareddata/xcschemes/FacebookShare.xcscheme
  Samples/Catalog/SwiftCatalog.xcodeproj/project.pbxproj
  Samples/Catalog/SwiftCatalog.xcodeproj/xcshareddata/xcschemes/SwiftCatalog.xcscheme
Labels: CLA Signed

#390 Resolved Bug in Share Source
  Sources/Share/Views/LikableObject.swift
Labels: CLA Signed, bug

#395 Converted to Configurations for Swift Version
  Configurations/FacebookCore.xcconfig
  Configurations/FacebookLogin.xcconfig
  Configurations/FacebookShare.xcconfig
  FacebookSwift.xcodeproj/project.pbxproj
  Samples/Catalog/Configurations/SwiftCatalog.xcconfig
  Samples/Catalog/SwiftCatalog.xcodeproj/project.pbxproj
Labels: CLA Signed

#402 Sourcery methods
  .gitattributes
  .sourcery.yml
  .swiftlint.yml
  .vscode/settings.json
  Brewfile
  Codegen/Generated/FacebookCore/ClassAndStructTemplate.generated.swift
  Codegen/Generated/FacebookCore/EnumTemplate.generated.swift
  Codegen/Templates/ClassAndStructTemplate.stencil
  Codegen/Templates/EnumTemplate.stencil
  Codegen/Templates/Shared/Comparable.stencil
  Codegen/Templates/Shared/Equatable.stencil
  Codegen/Templates/Shared/SetupInitializer.stencil
  Codegen/Templates/Shared/SetupMethods.stencil
  Codegen/Templates/Shared/SetupProperties.stencil
  FacebookCoreTests/Info.plist
  FacebookCoreTests/SourceryTests.swift
  FacebookSwift.xcodeproj/project.pbxproj
  FacebookSwift.xcodeproj/xcshareddata/xcschemes/FacebookCore.xcscheme
  FacebookSwift.xcodeproj/xcshareddata/xcschemes/FacebookCoreTests.xcscheme
  FacebookSwift.xcworkspace/contents.xcworkspacedata
  Samples/ObjCCatalog/ObjCCatalog/ObjCCatalog.xcodeproj/project.pbxproj
  Samples/ObjCCatalog/ObjCCatalog/ObjCCatalog.xcodeproj/xcshareddata/xcschemes/ObjCCatalog.xcscheme
  Samples/ObjCCatalog/ObjCCatalog/ObjCCatalog/CustomStruct.h
  Samples/ObjCCatalog/ObjCCatalog/ObjCCatalog/CustomStruct.m
  Samples/ObjCCatalog/ObjCCatalog/ObjCCatalog/Info.plist
  Samples/ObjCCatalog/ObjCCatalog/ObjCCatalog/ObjCCatalog.h
  Samples/ObjCCatalog/ObjCCatalog/ObjCCatalogTests/Info.plist
  Samples/ObjCCatalog/ObjCCatalog/ObjCCatalogTests/ObjCCatalogTests.m
  Sources/Core/CustomStruct.swift
  Sources/Core/Employee.swift
  Sources/Core/EmployeeClassification.swift
  Sources/Core/EmployeePayroll.swift
  Sources/Core/ObjCBridgeable.swift
  Sources/Core/StructWithGeneratedInitializer.swift
  scripts/travis/generate_objc.sh
Labels: CLA Signed

#405 Integrate code generation into core-conversion
  .gitattributes
  .sourcery.yml
  .swiftlint.yml
  .vscode/settings.json
  Brewfile
  Codegen/Generated/FacebookCore/ClassAndStructTemplate.generated.swift
  Codegen/Generated/FacebookCore/EnumTemplate.generated.swift
  Codegen/Templates/ClassAndStructTemplate.stencil
  Codegen/Templates/EnumTemplate.stencil
  Codegen/Templates/Shared/Comparable.stencil
  Codegen/Templates/Shared/Equatable.stencil
  Codegen/Templates/Shared/SetupInitializer.stencil
  Codegen/Templates/Shared/SetupMethods.stencil
  Codegen/Templates/Shared/SetupProperties.stencil
  FacebookCoreTests/Info.plist
  FacebookCoreTests/SourceryTests.swift
  FacebookSwift.xcodeproj/project.pbxproj
  FacebookSwift.xcodeproj/xcshareddata/xcschemes/FacebookCore.xcscheme
  FacebookSwift.xcworkspace/contents.xcworkspacedata
  Samples/ObjCCatalog/ObjCCatalog/ObjCCatalog.xcodeproj/project.pbxproj
  Samples/ObjCCatalog/ObjCCatalog/ObjCCatalog.xcodeproj/xcshareddata/xcschemes/ObjCCatalog.xcscheme
  Samples/ObjCCatalog/ObjCCatalog/ObjCCatalog/CustomStruct.h
  Samples/ObjCCatalog/ObjCCatalog/ObjCCatalog/CustomStruct.m
  Samples/ObjCCatalog/ObjCCatalog/ObjCCatalog/Info.plist
  Samples/ObjCCatalog/ObjCCatalog/ObjCCatalog/ObjCCatalog.h
  Samples/ObjCCatalog/ObjCCatalog/ObjCCatalogTests/Info.plist
  Samples/ObjCCatalog/ObjCCatalog/ObjCCatalogTests/ObjCCatalogTests.m
  Sources/Core/CustomStruct.swift
  Sources/Core/Employee.swift
  Sources/Core/EmployeeClassification.swift
  Sources/Core/EmployeePayroll.swift
  Sources/Core/ObjCBridgeable.swift
  scripts/travis/generate_objc.sh
Labels: CLA Signed

#407 Core Conversion Format
  Sources/Core/AccessTokenWallet.swift
  Sources/Core/CoreError.swift
  Sources/Core/EmptyDecodable.swift
  Sources/Core/Extensions/NotificationName+Extensions.swift
  Sources/Core/GraphRequest.swift
  Sources/Core/GraphRequestConnection.swift
  Sources/Core/GraphRequestSerializer.swift
  Sources/Core/Needs Conversion/Settings.swift
  Sources/Core/URLSessionTaskProxy.swift
  Sources/FacebookCoreTests/AccessTokenTests.swift
  Sources/FacebookCoreTests/ErrorConfigurationEntryTests.swift
  Sources/FacebookCoreTests/Extensions/RemoteErrorConfigurationEntry+Extensions.swift
  Sources/FacebookCoreTests/GraphConnectionProviderTests.swift
  Sources/FacebookCoreTests/GraphRequestSerializerTests.swift
  Sources/FacebookCoreTests/PermissionTests.swift
Labels: CLA Signed, accept2ship

#410 Removed old files
  FacebookCoreTests/Info.plist
  FacebookCoreTests/SourceryTests.swift
  Gemfile
Labels: CLA Signed, accept2ship

#413 Adding synx analysis job of travis build
  .travis.yml
  FacebookSwift.xcodeproj/project.pbxproj
  Gemfile.lock
  scripts/travis/synx.sh
Labels: CLA Signed

#414 Revert "Sourcery methods (#402)"
  .gitattributes
  .sourcery.yml
  .swiftlint.yml
  .vscode/settings.json
  Brewfile
  Codegen/Generated/FacebookCore/ClassAndStructTemplate.generated.swift
  Codegen/Generated/FacebookCore/EnumTemplate.generated.swift
  Codegen/Templates/ClassAndStructTemplate.stencil
  Codegen/Templates/EnumTemplate.stencil
  Codegen/Templates/Shared/Comparable.stencil
  Codegen/Templates/Shared/Equatable.stencil
  Codegen/Templates/Shared/SetupInitializer.stencil
  Codegen/Templates/Shared/SetupMethods.stencil
  Codegen/Templates/Shared/SetupProperties.stencil
  FacebookCoreTests/Info.plist
  FacebookCoreTests/SourceryTests.swift
  FacebookSwift.xcodeproj/project.pbxproj
  FacebookSwift.xcodeproj/xcshareddata/xcschemes/FacebookCore.xcscheme
  FacebookSwift.xcodeproj/xcshareddata/xcschemes/FacebookCoreTests.xcscheme
  FacebookSwift.xcworkspace/contents.xcworkspacedata
  Samples/ObjCCatalog/ObjCCatalog/ObjCCatalog.xcodeproj/project.pbxproj
  Samples/ObjCCatalog/ObjCCatalog/ObjCCatalog.xcodeproj/xcshareddata/xcschemes/ObjCCatalog.xcscheme
  Samples/ObjCCatalog/ObjCCatalog/ObjCCatalog/CustomStruct.h
  Samples/ObjCCatalog/ObjCCatalog/ObjCCatalog/CustomStruct.m
  Samples/ObjCCatalog/ObjCCatalog/ObjCCatalog/Info.plist
  Samples/ObjCCatalog/ObjCCatalog/ObjCCatalog/ObjCCatalog.h
  Samples/ObjCCatalog/ObjCCatalog/ObjCCatalogTests/Info.plist
  Samples/ObjCCatalog/ObjCCatalog/ObjCCatalogTests/ObjCCatalogTests.m
  Sources/Core/CustomStruct.swift
  Sources/Core/Employee.swift
  Sources/Core/EmployeePayroll.swift
  Sources/Core/ObjCBridgeable.swift
  Sources/Core/StructWithGeneratedInitializer.swift
  Sources/LinterRequired.swift
  scripts/travis/generate_objc.sh
Labels: CLA Signed

#427 Remove Sourcery from Core Conversion
  .gitattributes
  .sourcery.yml
  .swiftlint.yml
  .vscode/settings.json
  Brewfile
  Codegen/Generated/FacebookCore/ClassAndStructTemplate.generated.swift
  Codegen/Generated/FacebookCore/EnumTemplate.generated.swift
  Codegen/Templates/ClassAndStructTemplate.stencil
  Codegen/Templates/EnumTemplate.stencil
  Codegen/Templates/Shared/Comparable.stencil
  Codegen/Templates/Shared/Equatable.stencil
  Codegen/Templates/Shared/SetupInitializer.stencil
  Codegen/Templates/Shared/SetupMethods.stencil
  Codegen/Templates/Shared/SetupProperties.stencil
  FacebookSwift.xcodeproj/project.pbxproj
  FacebookSwift.xcodeproj/xcshareddata/xcschemes/FacebookCore.xcscheme
  FacebookSwift.xcworkspace/contents.xcworkspacedata
  Samples/ObjCCatalog/ObjCCatalog/ObjCCatalog.xcodeproj/project.pbxproj
  Samples/ObjCCatalog/ObjCCatalog/ObjCCatalog.xcodeproj/xcshareddata/xcschemes/ObjCCatalog.xcscheme
  Samples/ObjCCatalog/ObjCCatalog/ObjCCatalog/CustomStruct.h
  Samples/ObjCCatalog/ObjCCatalog/ObjCCatalog/CustomStruct.m
  Samples/ObjCCatalog/ObjCCatalog/ObjCCatalog/Info.plist
  Samples/ObjCCatalog/ObjCCatalog/ObjCCatalog/ObjCCatalog.h
  Samples/ObjCCatalog/ObjCCatalog/ObjCCatalogTests/Info.plist
  Samples/ObjCCatalog/ObjCCatalog/ObjCCatalogTests/ObjCCatalogTests.m
  Sources/Core/ObjCBridgeable.swift
  scripts/travis/generate_objc.sh
  scripts/travis/synx.sh
Labels: CLA Signed

#429 Removing swiftlint version check
  .swiftlint.yml
  Tests/Core/.swiftlint.yml
Labels: CLA Signed
