Repository facebook/facebook-swift-sdk, pull requests merged in 2019-03, with the labels that each got.

#344 Updated license comments for Configuration files
  Configurations/Shared/Common.xcconfig
  Configurations/Shared/Platform/iOS.xcconfig
  Configurations/Shared/Platform/macOS.xcconfig
  Configurations/Shared/Platform/tvOS.xcconfig
  Configurations/Shared/Platform/watchOS.xcconfig
  Configurations/Shared/Product/Application.xcconfig
  Configurations/Shared/Product/DynamicFramework.xcconfig
  Configurations/Shared/Product/LogicTests.xcconfig
  Configurations/Shared/Product/StaticFramework.xcconfig
  Configurations/Shared/Project/Debug.xcconfig
  Configurations/Shared/Project/Release.xcconfig
  Configurations/Shared/Warnings.xcconfig
Labels: CLA Signed

#343 General Code Maintenance
  .editorconfig
  .github_changelog_generator
  .gitmodules
  .jazzy.yaml
  .prettierrc.yml
  .swiftlint.yml
  Brewfile
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  Configurations/Shared/Common.xcconfig
  Configurations/Shared/Platform/iOS.xcconfig
  Configurations/Shared/Platform/macOS.xcconfig
  Configurations/Shared/Platform/tvOS.xcconfig
  Configurations/Shared/Platform/watchOS.xcconfig
  Configurations/Shared/Product/Application.xcconfig
  Configurations/Shared/Product/DynamicFramework.xcconfig
  Configurations/Shared/Product/LogicTests.xcconfig
  Configurations/Shared/Product/StaticFramework.xcconfig
  Configurations/Shared/Project/Debug.xcconfig
  Configurations/Shared/Project/Release.xcconfig
  Configurations/Shared/Warnings.xcconfig
  Gemfile.lock
  README.md
  SUPPORT.md
Labels: CLA Signed

#345 Merged Master
  Configurations/Shared/Product/StaticFramework.xcconfig
Labels: CLA Signed

#346 Introducing Permission enum
  FacebookSwift.xcodeproj/project.pbxproj
  Sources/Core/AccessToken.swift
  Sources/Core/FacebookCoreTests/AccessTokenTests.swift
  Sources/Core/FacebookCoreTests/Fixtures/AccessTokenFixtures.swift
  Sources/Core/FacebookCoreTests/PermissionTests.swift
  Sources/Core/Permission.swift
Labels: CLA Signed

#341 file_name rule does not play nice with many extensions and namespaces
  .swiftlint.yml
Labels: CLA Signed

#349 Release 1.0
  .editorconfig
  .github_changelog_generator
  .gitmodules
  .jazzy.yaml
  .prettierrc.yml
  .swiftlint.yml
  Brewfile
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  Configurations/Shared/Common.xcconfig
  Configurations/Shared/Platform/iOS.xcconfig
  Configurations/Shared/Platform/macOS.xcconfig
  Configurations/Shared/Platform/tvOS.xcconfig
  Configurations/Shared/Platform/watchOS.xcconfig
  Configurations/Shared/Product/Application.xcconfig
  Configurations/Shared/Product/DynamicFramework.xcconfig
  Configurations/Shared/Product/LogicTests.xcconfig
  Configurations/Shared/Product/StaticFramework.xcconfig
  Configurations/Shared/Project/Debug.xcconfig
  Configurations/Shared/Project/Release.xcconfig
  Configurations/Shared/Warnings.xcconfig
  Gemfile.lock
  README.md
  SUPPORT.md
Labels: CLA Signed, enhancement

#352 Removing incorrect swiftlint change
  .swiftlint.yml
Labels: CLA Signed

#347 Add error type
  FacebookSwift.xcodeproj/project.pbxproj
  ObjcReference/FBSDKCoreKit/FBSDKCoreKit/Info.plist
  Sources/Core/CoreError.swift
  Sources/Core/FBError.swift
  Sources/FacebookCoreTests/CoreErrorTests.swift
  Sources/FacebookCoreTests/FBErrorTests.swift
Labels: CLA Signed

#351 Adding enum for debug parameters
  .swiftlint.yml
  FacebookSwift.xcodeproj/project.pbxproj
  Sources/Core/GraphApiDebugParameter.swift
  Sources/FacebookCoreTests/GraphApiDebugParameterTests.swift
Labels: CLA Signed

#363 Encourages use of API Design Guidelines
  CONTRIBUTING.md
Labels: accept2ship, easy

#358 Making token documentation more resiliant to formatting changes
  Sources/Core/AccessToken.swift
Labels: CLA Signed

#364 Core conversion swiftlint autocorrect
  Sources/Core/GraphRequestQueryItemBuilder.swift
  Sources/FacebookCoreTests/GraphRequestQueryItemBuilderTests.swift
Labels: CLA Signed

#365 Localization
  FacebookSwift.xcodeproj/project.pbxproj
  Sources/Core/ErrorRecoveryStrings.swift
  Sources/Core/Localizable.swift
  Sources/FacebookCoreTests/ErrorRecoveryStringTests.swift
  Sources/FacebookCoreTests/Helpers/LocalizedStringValidation.swift
  Sources/FacebookCoreTests/Helpers/SampleLocalizedStrings.swift
  Sources/FacebookCoreTests/LocalizableStrings.strings
  Sources/FacebookCoreTests/LocalizationsTests.swift
  Sources/en.lproj/LocalizableStrings.strings
Labels: CLA Signed

#371 Adding default configuration
  FacebookSwift.xcodeproj/project.pbxproj
  Sources/Core/ErrorHandling/ErrorConfiguration.swift
  Sources/FacebookCoreTests/DefaultErrorConfigurationTests.swift
Labels: CLA Signed

#374 Stronger typing for GraphPaths
  FacebookSwift.xcodeproj/project.pbxproj
  Sources/Core/GraphPath.swift
  Sources/Core/GraphRequest.swift
  Sources/Core/URLBuilder.swift
  Sources/FacebookCoreTests/GraphPathTests.swift
  Sources/FacebookCoreTests/GraphRequestMetadataTests.swift
  Sources/FacebookCoreTests/GraphRequestTests.swift
  Sources/FacebookCoreTests/URLBuilderTests.swift
Labels: CLA Signed

#375 Removing files that are not part of project
  FacebookSwift.xcodeproj/project.pbxproj
  Sources/Core/ErrorRecoveryConfiguration.swift
  Sources/Core/RemoteErrorConfigurationDecodingError.swift
  Sources/Core/RemoteErrorRecoveryCodes.swift
  Sources/Core/RemoteErrorRecoveryConfiguration.swift
  Sources/Core/RemoteErrorRecoveryConfigurationList.swift
  Sources/FacebookCoreTests/ErrorRecoveryConfigurationTests.swift
  Sources/FacebookCoreTests/RemoteErrorConfigurationTests.swift
  Sources/FacebookCoreTests/URLBuilderTests.swift
Labels: CLA Signed
